# AUTOGENERATED from a merge of:
#   - vacp2p/nim-libp2p @ v2.1.4  nix/deps.nix   (libp2p transitive Nim deps)
#   - vacp2p/nim-libp2p master    nix/cbind-deps.nix   (cbor_serialization, taskpools, ffi)
#   - fresh nix-prefetch-git for  libp2p, libp2p_mix, mix_rln_spam_protection
#
# Missing: mix-rln plugin's own transitive additions beyond libp2p's set
# (e.g. secp256k1, json_serialization are already covered here).
#
# To regenerate after bumping any pin, run tools/regen-cbind-deps.py.
{ pkgs }:

{
  bearssl = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-bearssl";
    rev = "22c6a76ce015bc07e011562bdcfc51d9446c1e82";
    sha256 = "1cvdd7lfrpa6asmc39al3g4py5nqhpqmvypc36r5qyv7p5arc8a3";
    fetchSubmodules = true;
  };

  boringssl = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-boringssl";
    rev = "e77caabae78fbc9aa5b78a0a521181b077c82571";
    sha256 = "15k4dqh1hlcpq9zm30lpr728h7apdmgm22xzqhdm3clq9kia6fr8";
    fetchSubmodules = true;
  };

  cbor_serialization = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-cbor-serialization";
    rev = "1664160e04d153573373afddc552b9cbf6fbe4dc";
    sha256 = "0c1rj4fk0fcqvsf0yqhxvm8h10aww75gi4yfsjhlczh88ypywii2";
    fetchSubmodules = true;
  };

  chronicles = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronicles";
    rev = "27ec507429a4eb81edc20f28292ee8ec420be05b";
    sha256 = "1xx9fcfwgcaizq3s7i3s03mclz253r5j8va38l9ycl19fcbc96z9";
    fetchSubmodules = true;
  };

  chronos = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-chronos";
    rev = "45f43a9ad8bd8bcf5903b42f365c1c879bd54240";
    sha256 = "1v1n59zfzznp97pvwgs9kf136bqmv4x2s2y9f24msspa7qv27w39";
    fetchSubmodules = true;
  };

  faststreams = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-faststreams";
    rev = "50889cd16ec8771106cdd0eeea460039e8571e06";
    sha256 = "1hd4bhvw5lzwg924i8dif5mi61h0ayiplq38djvrdbfsjdhw2zvw";
    fetchSubmodules = true;
  };

  ffi = pkgs.fetchgit {
    url = "https://github.com/logos-messaging/nim-ffi";
    rev = "b95e2b04a63fbd417938bf3ec0ac14be7935e21b";
    sha256 = "16iynxgls3w9gsy79m1z29s6r8d09xpzsm7rl29q72gs0n9i26m0";
    fetchSubmodules = true;
  };

  httputils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-http-utils";
    rev = "f142cb2e8bd812dd002a6493b6082827bb248592";
    sha256 = "03msj4zdxraz4qx9cidb17g7v0asazxv91nng6xxbzjxz0qaqxw6";
    fetchSubmodules = true;
  };

  json_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-json-serialization";
    rev = "c343b0e243d9e17e2c40f3a8a24340f7c4a71d44";
    sha256 = "0i8sq51nqj8lshf6bfixaz9a7sq0ahsbvq3chkxdvv4khsqvam91";
    fetchSubmodules = true;
  };

  libp2p = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-libp2p";
    rev = "v2.1.4";
    sha256 = "0sd7w12bx6w3d0f40wm65xj4cc746ijw583x3lgxrcgh9ssmjpck";
    fetchSubmodules = true;
  };

  libp2p_mix = pkgs.fetchgit {
    url = "https://github.com/logos-co/nim-libp2p-mix";
    rev = "c387ca67cf477dc53ec6228027c45d8eda067917";
    sha256 = "0rzcp1z9kvqcf0kgq1n2ywm7wz6qina0yj157vgwzxi3104yk6ba";
    fetchSubmodules = true;
  };

  lsquic = pkgs.fetchgit {
    url = "https://github.com/vacp2p/nim-lsquic";
    rev = "3813b849d70edbef24dac3926b32949029721fdc";
    sha256 = "016r3i7xj5mriaf199xr91j1f8312s89zgp66fiy9bj1j1i22yp7";
    fetchSubmodules = true;
  };

  metrics = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-metrics";
    rev = "b4b70a88fe1755d281366cbc3f22d7515240d192";
    sha256 = "0y85na0ah53zk4la8jxjwml9l6269bv21daqn8ylcsd2wg463qs6";
    fetchSubmodules = true;
  };

  mix_rln_spam_protection = pkgs.fetchgit {
    url = "https://github.com/logos-co/mix-rln-spam-protection-plugin";
    rev = "135182b72c16d3bd9c2d06087d84303272e4d1eb";
    sha256 = "1d44iz8vg6aaa9y7ba36x19gspwmixa5825xycp1yn21psyil507";
    fetchSubmodules = true;
  };

  nat_traversal = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-nat-traversal";
    rev = "860e18c37667b5dd005b94c63264560c35d88004";
    sha256 = "0319k5bbl468phwfnvlrh7725sc80rnf7m9gyj0i3cb5hb9q78bs";
    fetchSubmodules = true;
  };

  nimcrypto = pkgs.fetchgit {
    url = "https://github.com/cheatfate/nimcrypto";
    rev = "b3dbc9c4d08e58c5b7bfad6dc7ef2ee52f2f4c08";
    sha256 = "1v4rz42lwcazs6isi3kmjylkisr84mh0kgmlqycx4i885dn3g0l4";
    fetchSubmodules = true;
  };

  npeg = pkgs.fetchgit {
    url = "https://github.com/zevv/npeg";
    rev = "409f6796d0e880b3f0222c964d1da7de6e450811";
    sha256 = "1h2f5znbpa3svk7wsw2axn8f7f59d23xq85z148kiv6fqh0ffwbm";
    fetchSubmodules = true;
  };

  protobuf_serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-protobuf-serialization";
    rev = "f45476a3c1f4e7bff73845e6450d686be040ddeb";
    sha256 = "1b4cnlkqlmnhx5gd4smiz4xwaj2zmyccc2q20r26gcqfiyp9na0v";
    fetchSubmodules = true;
  };

  results = pkgs.fetchgit {
    url = "https://github.com/arnetheduck/nim-results";
    rev = "df8113dda4c2d74d460a8fa98252b0b771bf1f27";
    sha256 = "1h7amas16sbhlr7zb7n3jb5434k98ji375vzw72k1fsc86vnmcr9";
    fetchSubmodules = true;
  };

  secp256k1 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-secp256k1";
    rev = "d8f1288b7c72f00be5fc2c5ea72bf5cae1eafb15";
    sha256 = "1qjrmwbngb73f6r1fznvig53nyal7wj41d1cmqfksrmivk2sgrn2";
    fetchSubmodules = true;
  };

  serialization = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-serialization";
    rev = "b0f2fa32960ea532a184394b0f27be37bd80248b";
    sha256 = "0wip1fjx7ka39ck1g1xvmyarzq1p5dlngpqil6zff8k8z5skiz27";
    fetchSubmodules = true;
  };

  stew = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-stew";
    rev = "4382b18f04b3c43c8409bfcd6b62063773b2bbaa";
    sha256 = "0mx9g5m636h3sk5pllcpylk51brf7lx91izx3gc23k3ih3hrxyk2";
    fetchSubmodules = true;
  };

  taskpools = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-taskpools";
    rev = "9e8ccc754631ac55ac2fd495e167e74e86293edb";
    sha256 = "1y78l33vdjxmb9dkr455pbphxa73rgdsh8m9gpkf4d9b1wm1yivy";
    fetchSubmodules = true;
  };

  testutils = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-testutils";
    rev = "6ce5e5e2301ccbc04b09d27ff78741ff4d352b4d";
    sha256 = "1vbkr6i5yxhc2ai3b7rbglhmyc98f99x874fqdp6a152a6kqgwxy";
    fetchSubmodules = true;
  };

  unittest2 = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-unittest2.git";
    rev = "26f2ef3ae0ec72a2a75bfe557e02e88f6a31c189";
    sha256 = "1n8n36kad50m97b64y7bzzknz9n7szffxhp0bqpk3g2v7zpda8sw";
    fetchSubmodules = true;
  };

  websock = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-websock";
    rev = "387a8eb7e961e8fdd3b1a717d36bc53b55e4dc5d";
    sha256 = "1v0m3x96fbp9jdzsys6mbxxc2xw3k3dqiv7wksfla89gc6z8w377";
    fetchSubmodules = true;
  };

  zlib = pkgs.fetchgit {
    url = "https://github.com/status-im/nim-zlib";
    rev = "190246aa0bb6569781370964fa2faa474203d6dd";
    sha256 = "0x5l55gwzb1ay3k9inmi1g25jiv7flry247fcwd8rw3zw9pgchfv";
    fetchSubmodules = true;
  };
}
