#!/usr/bin/env python3
"""Regenerate nix/cbind-deps.nix.

Merges the sha256s already computed upstream (nim-libp2p/nix/deps.nix at v2.1.4
+ nim-libp2p master's cbind-deps.nix) with fresh nix-prefetch-git results for
our three additional pins (nim-libp2p at v2.1.4 as a Nim-source dep,
nim-libp2p-mix at the pinned SHA, mix-rln-spam-protection-plugin).

Requires local clones under /home/r/logos-co/.ref/:
  - nim-libp2p (master)  — for nix/cbind-deps.nix
  - nim-libp2p at v2.1.4 — for nix/deps.nix (clone as ./nim-libp2p-v214)

Usage:
  python3 tools/regen-cbind-deps.py > nix/cbind-deps.nix
"""

import re
import subprocess
import sys
from pathlib import Path

REF = Path("/home/r/logos-co/.ref")

FETCHGIT = re.compile(
    r"(\w+)\s*=\s*pkgs\.fetchgit\s*\{\s*"
    r'url\s*=\s*"([^"]+)";\s*'
    r'rev\s*=\s*"([^"]+)";\s*'
    r'sha256\s*=\s*"([^"]+)";',
    re.DOTALL,
)

EXTRA_PINS = {
    "libp2p": (
        "https://github.com/vacp2p/nim-libp2p",
        "v2.1.4",
    ),
    "libp2p_mix": (
        "https://github.com/logos-co/nim-libp2p-mix",
        "c387ca67cf477dc53ec6228027c45d8eda067917",
    ),
    "mix_rln_spam_protection": (
        "https://github.com/logos-co/mix-rln-spam-protection-plugin",
        "135182b72c16d3bd9c2d06087d84303272e4d1eb",
    ),
}


def load_nix_deps(path: Path) -> dict[str, tuple[str, str, str]]:
    return {
        m.group(1): (m.group(2), m.group(3), m.group(4))
        for m in FETCHGIT.finditer(path.read_text())
    }


def prefetch(url: str, rev: str) -> str:
    """Runs nix-prefetch-git; returns the sha256 (base32)."""
    result = subprocess.run(
        [
            "nix-prefetch-git",
            "--url", url,
            "--rev", rev,
            "--fetch-submodules",
            "--quiet",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    for line in result.stdout.splitlines():
        if '"sha256"' in line:
            return line.split('"')[3]
    raise RuntimeError(f"no sha256 in output for {url}@{rev}")


def main() -> int:
    merged: dict[str, tuple[str, str, str]] = {}
    for src in (REF / "nim-libp2p-v214" / "nix" / "deps.nix",
                REF / "nim-libp2p" / "nix" / "cbind-deps.nix"):
        for name, entry in load_nix_deps(src).items():
            merged.setdefault(name, entry)
    # nim itself comes from pkgs.nim-2_2, not as a Nim source path
    merged.pop("nim", None)

    for name, (url, rev) in EXTRA_PINS.items():
        print(f"nix-prefetch-git {url} @ {rev}", file=sys.stderr)
        merged[name] = (url, rev, prefetch(url, rev))

    out = [
        "# AUTOGENERATED by tools/regen-cbind-deps.py",
        "{ pkgs }:",
        "",
        "{",
    ]
    for name in sorted(merged):
        url, rev, sha = merged[name]
        out.extend([
            f"  {name} = pkgs.fetchgit {{",
            f'    url = "{url}";',
            f'    rev = "{rev}";',
            f'    sha256 = "{sha}";',
            f"    fetchSubmodules = true;",
            f"  }};",
            "",
        ])
    out.append("}")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
